#!/usr/bin/env node
/**
 * Ensure the published CLI entry has a shebang and executable bit.
 * npm bin linking relies on both for a clean global install.
 *
 * Also writes dist/.npmignore so source maps are stripped when
 * package.json "files" includes the whole dist/ directory (root
 * .npmignore alone does not always filter nested files under files:).
 */
import { chmodSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const distDir = path.join(root, "dist");
const entry = path.join(distDir, "index.js");

if (!existsSync(entry)) {
  console.error("[postbuild-bin] missing dist/index.js — run tsc first");
  process.exit(1);
}

const SHEBANG = "#!/usr/bin/env node\n";
let body = readFileSync(entry, "utf8");
if (!body.startsWith("#!")) {
  body = SHEBANG + body;
  writeFileSync(entry, body, "utf8");
}

chmodSync(entry, 0o755);

// Nested ignore: required for files:["dist"] packs on modern npm.
const distNpmIgnore = [
  "# Generated by scripts/postbuild-bin.mjs — do not edit by hand",
  "*.map",
  "**/*.map",
  "**/*.js.map",
  "**/*.d.ts.map",
  "__tests__/",
  "**/*.test.js",
  "**/*.test.d.ts",
  "",
].join("\n");
writeFileSync(path.join(distDir, ".npmignore"), distNpmIgnore, "utf8");

console.log("[postbuild-bin] dist/index.js shebang+mode 0755 ok; dist/.npmignore written");
